version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: msim
      POSTGRES_USER: msim
      POSTGRES_DB: msim
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./src/msim:/src
    environment:
      DJANGO_DEBUG: 'true'
      DJANGO_DATABASES: |
        {
          "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": "db",
            "USER": "msim",
            "PASSWORD": "msim",
            "NAME": "msim"
          }
        }
    command: uvicorn --reload --host 0.0.0.0 --port 54748 _.asgi:application
    ports:
      - 54748:54748
