# Generated by Django 3.0.3 on 2020-05-06 05:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('term', models.PositiveSmallIntegerField()),
                ('initial_period', models.PositiveSmallIntegerField()),
                ('interest_rate_initial', models.DecimalField(decimal_places=5, max_digits=5)),
                ('interest_rate_thereafter', models.DecimalField(decimal_places=5, max_digits=5)),
                ('income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActualThereafterPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualthereafterpayment', to='mortgages.Mortgage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActualInitialPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualinitialpayment', to='mortgages.Mortgage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
