# Generated by Django 3.0.3 on 2020-05-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualinitialpayment',
            name='mortgage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actualinitialpayment', to='mortgages.Mortgage'),
        ),
        migrations.AlterField(
            model_name='actualthereafterpayment',
            name='mortgage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actualthereafterpayment', to='mortgages.Mortgage'),
        ),
    ]
