# Generated by Django 3.0.3 on 2020-05-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_auto_20200506_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.PositiveSmallIntegerField()),
                ('mortgage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overpayments', to='mortgages.Mortgage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.PositiveSmallIntegerField()),
                ('mortgage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancys', to='mortgages.Mortgage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
