# Generated by Django 3.0.3 on 2020-05-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0003_discrepancy_overpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discrepancy',
            unique_together={('mortgage', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='overpayment',
            unique_together={('mortgage', 'month')},
        ),
    ]
