# Generated by Django 3.0.3 on 2020-05-08 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0004_auto_20200506_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancy',
            name='mortgage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancys', to='mortgages.Mortgage'),
        ),
        migrations.AlterField(
            model_name='overpayment',
            name='mortgage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overpayments', to='mortgages.Mortgage'),
        ),
    ]
